weights: runs/train/petface_yolov5s_2cls_clean2/weights/best.pt
cfg: models/petface_yolov5s.yaml
data: data/pet_faces.yaml
hyp: data/hyp.finetune_lrdrop.yaml
epochs: 10
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
save_period: 1
bucket: ''
cache_images: false
image_weights: false
device: cpu
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 0
project: runs/train
name: petface_yolov5s_2cls_clean2_finetune
exist_ok: true
total_batch_size: 16
world_size: 1
global_rank: -1
save_dir: runs/train/petface_yolov5s_2cls_clean2_finetune
