weights: ''
cfg: models/petface_yolov5s.yaml
data: data/pet_faces.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
save_period: 1
bucket: ''
cache_images: false
image_weights: false
device: mps
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 4
project: runs/train
name: petface_yolov5s_2cls_clean
exist_ok: false
total_batch_size: 32
world_size: 1
global_rank: -1
save_dir: runs/train/petface_yolov5s_2cls_clean2
